#
- name: create vhosts folder
  file: path="{{ nginx_conf_path }}/{{ nginx_vhosts_path }}" state=directory owner="root"  group="{{ nginx_root_group }}" mode=0644
  tags: [ 'configuration','nginx' ]

- name: create vhosts test folder
  file: path="{{ nginx_conf_path }}/{{ nginx_vhosts_path_test_mode }}" state=directory owner="root" group="{{ nginx_root_group }}" mode=0644
  tags: [ 'configuration','nginx' ]

- name: create proxy cache folders
  file: path="{{ item }}" state=directory owner="{{ nginx_user }}" group="{{ nginx_root_group }}" mode=0755
  with_items: "{{ nginx_proxy_cache_path.keys() }}" 
  when:  nginx_proxy_cache_path != []
  tags: [ 'configuration','nginx' ]

- name: create newsyslogconf folder
  file: path=/usr/local/etc/newsyslog.conf.d state=directory owner="root" group="{{ nginx_root_group }}" mode=0755
  when:
    ansible_os_family == 'FreeBSD'
  tags: [ 'configuration','nginx' ]
